### ISSUE TITLE
Handling spaces in filenames of ffmpeg command 

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [WritingMinds/ffmpeg-android-java#35] opened 2015-08-03 04:14 UTC
I am using below ffmpeg command to cut videos.It works fine for video file names which doesn't have spaces but didn't worked for filenames having spaces..

    execFFmpegBinary("-i " + path + " -ss " + startMs / 1000 + " -to " + endMs / 1000 + " -strict -2 -async 1 " + dest.getAbsolutePath());

where  `path` is the path of original video.

`startMs` is the initial time of video form where you want to cut(start time of cropped video)

`endMs` is the time of video upto which you want to cut(end time of cropped video)

`dest` is the path where you want to save the cut/cropped video
 

The problem is with source path(path).I have seen [this][1] answer.But here i don't know the complete path since I am fetching paths of all the videos from storage. I need to handle spaces in filenames.
For resolving that i tried using string formatter as shown in below code .But with that it didn't worked in both cases.Where am i going wrong and how can i resolve the issue?

    String command = String.format("-i \"%s\" -ss %d -to %d -strict -2 -async 1 \"%s\" ",path,startMs / 1000 , endMs / 1000, dest.getAbsolutePath());
    execFFmpegBinary(command);

  [1]: http://stackoverflow.com/questions/22766111/ffmpeg-not-working-with-filenames-that-have-whitespace?lq=1

**Comment by kfeoktistoff** [comment] 2015-09-15 17:10
Hi bhuvneshvarma,

The problem is that parameters should be passed in String array to getRuntime.exec() method. In this case parameters with spaces will be passed correctly. The explanation is [here.](http://stackoverflow.com/a/14078844)

The [PR](https://github.com/WritingMinds/ffmpeg-android-java/pull/17) with the fix is already merged but the updated version of the library is not in Maven because for unknown reason...

**Closed** 2016-05-06 00:18 UTC

**Comment by chaudharybharat** [comment] 2017-06-29 11:37
FFmpeg command not run when path inside whitespace i have pass in command value in array string 
I had apply path inside \ but still not working.

 have you any idea or solution please help me
